name: Database Test
on: [ push, pull_request ]

jobs:
  windows:
    runs-on: windows-latest
    steps:

      - name: Start PostgreSQL
        run: |
          sc config postgresql-x64-14 start= demand
          net start postgresql-x64-14
          & $Env:PGBIN/createdb -U postgres mirai

      - name: Start MySQL
        run: |
          mysqld --initialize-insecure
          mysqld --install
          net start MySQL
          mysqladmin -uroot create mirai
          mysqladmin -uroot password root

      - name: Start MSSQL
        run: |
          choco install sql-server-express --no-progress -y
          sc qc 'MSSQL$SQLEXPRESS'
          sqlcmd -S .\SQLEXPRESS -Q "CREATE DATABASE mirai"

      - name: Enable the TCP protocol on MSSQL$SQLEXPRESS
        run: |
          # https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/enable-or-disable-a-server-network-protocol
          $Wmi = New-Object ('Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer').
          # List the object properties, including the instance names.  
          $Wmi
          # Enable the TCP protocol on the default instance.  
          $Uri = "ManagedComputer[@Name='$env:COMPUTERNAME']/ServerInstance[@Name='SQLEXPRESS']/ServerProtocol[@Name='Tcp']"
          $Tcp = $wmi.GetSmoObject($Uri)
          $Tcp.IsEnabled = $true
          $Tcp.Alter()
          $Tcp

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew clean --scan

      - name: Build all
        run: ./gradlew assemble --scan

      - name: SqliteTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.SqliteTest" --scan --info

      - name: H2Test
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.H2Test" --scan --info

      - name: MysqlTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.MysqlTest" --scan --info

      - name: PostgreSqlTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.PostgreSqlTest" --scan --info

      - name: MSSqlTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.MSSqlTest" --scan --info

  macos:
    runs-on: macos-latest
    steps:

      - name: Start PostgreSQL
        run: |
          brew info postgresql
          brew services start postgresql -v
          tail -n 100 /usr/local/var/log/postgres*.log
        env:
          PGUSER: postgres
          PGDATABASE: postgres

      - name: Start MySQL
        run: |
          brew install mysql
          brew info mysql
          brew services restart mysql -v

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew clean --scan

      - name: Set Database User
        run: |
          createuser -U runner -s postgres
          createdb mirai
          psql -c "ALTER USER postgres PASSWORD 'root';"
          mysqladmin -uroot create mirai
          mysqladmin -uroot password root
        env:
          PGUSER: postgres
          PGDATABASE: postgres

      - name: Build all
        run: ./gradlew assemble --scan

      - name: SqliteTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.SqliteTest" --scan --info

      - name: H2Test
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.H2Test" --scan --info

      - name: MysqlTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.MysqlTest" --scan --info

      - name: PostgreSqlTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.PostgreSqlTest" --scan --info

  linux:
    runs-on: ubuntu-latest
    steps:

      - name: Start PostgreSql
        run: |
          sudo systemctl start postgresql
          sudo -u postgres createdb mirai
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'root';"

      - name: Start MySQL
        run: |
          sudo systemctl start mysql.service
          mysqladmin -u root -proot create mirai

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew clean --scan

      - name: Build all
        run: ./gradlew assemble --scan

      - name: SqliteTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.SqliteTest" --scan --info

      - name: H2Test
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.H2Test" --scan --info

      - name: MysqlTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.MysqlTest" --scan --info

      - name: PostgreSqlTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.PostgreSqlTest" --scan --info