name: Database Test
on: [ push, pull_request ]

jobs:
  windows:
    runs-on: windows-latest
    steps:

      - name: Start PostgreSQL
        run: |
          sc config postgresql-x64-14 start= demand
          sc start postgresql-x64-14

      - name: Start MySQL
        run: |
          mysqld --initialize-insecure
          mysqld --install
          sc start MySQL

      - name: Start MSSQL
        run: |
          choco install sql-server-express --no-progress -y
          sc qc 'MSSQL$SQLEXPRESS'

      # https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/enable-or-disable-a-server-network-protocol
      - name: Enable the TCP protocol on MSSQL$SQLEXPRESS
        run: |
          [reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.SqlWmiManagement")
          $ManagedComputer = New-Object -TypeName 'Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer'
          $ManagedComputer
          $ServerInstance = $ManagedComputer.ServerInstances['SQLEXPRESS']
          $Tcp = $ServerInstance.ServerProtocols['Tcp']
          $Tcp.IsEnabled = $True
          $Tcp.Alter()
          $Service = $ManagedComputer.Services['MSSQL$SQLEXPRESS']
          $Service.Stop()
          $Service.Refresh()
          $Service.Start()
          $Service
          $Tcp.Refresh()
          $Tcp
          $Tcp.IPAddresses

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Create Database and Account
        run: |
          & $Env:PGBIN/createdb -U postgres mirai
          mysqladmin -uroot create mirai
          mysqladmin -uroot password root
          sqlcmd -S tcp:127.0.0.1\SQLEXPRESS,1433 -Q "CREATE DATABASE mirai"

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew clean --scan

      - name: Build all
        run: ./gradlew assemble --scan

      - name: SqliteTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.SqliteTest" --scan --info

      - name: H2Test
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.H2Test" --scan --info

      - name: MySqlTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.MySqlTest" --scan --info

      - name: PostgreSqlTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.PostgreSqlTest" --scan --info

      - name: MSSqlTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.MSSqlTest" --scan --info

  macos:
    runs-on: macos-latest
    steps:

      - name: Start PostgreSQL
        run: |
          brew info postgresql
          brew services start postgresql -v
          tail -n 100 /usr/local/var/log/postgres*.log
        env:
          PGUSER: postgres
          PGDATABASE: postgres

      - name: Start MySQL
        run: |
          brew install mysql
          brew info mysql
          brew services restart mysql -v

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew clean --scan

      - name: Set Database User
        run: |
          createuser -U runner -s postgres
          createdb mirai
          psql -c "ALTER USER postgres PASSWORD 'root';"
          mysqladmin -uroot create mirai
          mysqladmin -uroot password root
        env:
          PGUSER: postgres
          PGDATABASE: postgres

      - name: Build all
        run: ./gradlew assemble --scan

      - name: SqliteTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.SqliteTest" --scan --info

      - name: H2Test
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.H2Test" --scan --info

      - name: MySqlTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.MySqlTest" --scan --info

      - name: PostgreSqlTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.PostgreSqlTest" --scan --info

  linux:
    runs-on: ubuntu-latest
    steps:

      - name: Start PostgreSql
        run: |
          sudo systemctl start postgresql
          sudo -u postgres createdb mirai
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'root';"

      - name: Start MySQL
        run: |
          sudo systemctl start mysql.service
          mysqladmin -u root -proot create mirai

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew clean --scan

      - name: Build all
        run: ./gradlew assemble --scan

      - name: SqliteTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.SqliteTest" --scan --info

      - name: H2Test
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.H2Test" --scan --info

      - name: MySqlTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.MySqlTest" --scan --info

      - name: PostgreSqlTest
        run: ./gradlew test --tests "xyz.cssxsh.mirai.hibernate.entry.PostgreSqlTest" --scan --info